### ISSUE TITLE
Menu and page flickering

### ISSUE THREAD

**Issue by thewebartisan7** [torrix/laravel-uikit#2]
Thanks for this starting point.

I would like to ask about some strange page flickering for a moment during page load, as you can see on below gif the menu show unstyled links and then load styled, seem like something is initialized by JS, but can't see this behaviour on UIkit demo.

https://gyazo.com/6a6b6c045919ced8d3b8629ba354048c

**Comment by mattfletcher** [comment]
Sorry I've only just seen this issue. I suspect there's a class being added by JS. I've seen something similar where adding the 'uk-grid' attribute will add the 'uk-grid' class, but only once the JS kicks in. The fix is to add both the class and the attribute yourself. I'll try and work out what it is, and update the boilerplate.

**Comment by mattfletcher** [comment]
@thewebartisan7 it looks like it's because the homepage doesn't have enough content to need a scrollbar.

`html {
    overflow-y:scroll;
}`

in your app.scss should be enough to fix that and force a scrollbar even if one isn't needed. I'll add it in the next time I make a release.

**Comment by thewebartisan7** [comment]
I notice that is caused by uk-* attributes that manipulate DOM such as you mention uk-grid, but also uk-margin, uk-icon, etc.

I remove much of them that I can, but seem several are required so I still notice a small flickering.

After checking again UIKit demo, is the same for their demo, but is hard to notice because they use vuejs so page seem pre-built or similar. But in certain part of page you can see it.

**Comment by mattfletcher** [comment]
Closing as I cannot replicate, and it sounds like any issue might be with UIkit itself
