### ISSUE TITLE
Syntax error in LaravelUikitServiceProvider.php line 13

### ISSUE THREAD

**Issue by sjys** [torrix/laravel-uikit#5]
In LaravelUikitServiceProvider.php line 13:
                                                                 
  syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'  
                                                                 

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by mattfletcher** [comment]
What version of PHP are you using please?

**Comment by sjys** [comment]
I'm using PHP 7.3.22

**Comment by macedodebrito** [comment]
same with PHP 7.3.15

**Comment by patriksh** [comment]
PHP 7.4 is the minimum required version due to anonymous arrow functions.

**Comment by mattfletcher** [comment]
Minimum PHP version now listed as 8.2 in composer.json so as to make the version requirements clear.
